samples:
    - F1D
    - F2D
    - F3D
    - F4D
    - F6D
    - F7D
    - F8D
    - F9D
    - F10D
    - M2D
    - M3D
    - M4D
    - M5D
    - M6D
    - M7D
    - M8D
    - M9D
    - RF1D
    - RF2D
    - RF3D
    - RF4D
    - RF5D
    - RF6D
    - RF7D
    - RF8D
    - RF10D
    - RM1D
    - RM2D
    - RM3D
    - RM4D
    - RM5D
    - RM6D
    - RM7D
    - RM8D
    - RU5D




combos:
  - _L1_NovaSeq6000
  - _L2_HiSeq4000
  - _L2_NovaSeq6000