samples:
    - F10D
    - F1D
    - F2D
    - F3D
    - F4D
    - F6D
    - F7D
    - F8D
    - F9D
    - M2D
    - M3D
    - M4D
    - M5D
    - M6D
    - M7D
    - M8D
    - M9D



combos:
  - _L1_NovaSeq6000
  - _L2_HiSeq4000
  - _L2_NovaSeq6000